### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'FEATURES')

### ISSUE THREAD

**Issue by brunoreis** [storybookjs/testing-library#32]
### Describe the bug

I'm seeing the following error, when trying to see a story that has a `.play` assigned to it and it calls `within`: 
```
Cannot read properties of undefined (reading 'FEATURES')
TypeError: Cannot read properties of undefined (reading 'FEATURES')
    at ./node_modules/@storybook/instrumenter/dist/esm/instrumenter.js (http://www.aritimetica.local.com.br/storybook/vendors-node_modules_storybook_testing-library_dist_esm_index_js.iframe.bundle.js:174:93)
    at __webpack_require__ (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:28:33)
    at fn (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:328:25)
    at ./node_modules/@storybook/testing-library/dist/esm/index.js (http://www.aritimetica.local.com.br/storybook/vendors-node_modules_storybook_testing-library_dist_esm_index_js.iframe.bundle.js:1075:81)
    at __webpack_require__ (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:28:33)
    at fn (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:328:25)
    at ./app/Header/Header.stories.tsx (http://www.aritimetica.local.com.br/storybook/Header-Header-stories.iframe.bundle.js:24:84)
    at __webpack_require__ (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:28:33)
    at fn (http://www.aritimetica.local.com.br/storybook/runtime~main.iframe.bundle.js:328:25)
    at http://www.aritimetica.local.com.br/storybook/main.iframe.bundle.js:62:10
```

The story works fine, but if I add the `.play` and call `within`, I see that error. This is the line throwing the error: 
```
LoggedInOpening.play = async ({ canvasElement }) => {
    const canvas = within(canvasElement)```
### Steps to reproduce the behavior
```

### Expected behavior

`.play` should run the interaction

### Screenshots and/or logs
![Screen Shot 2023-01-11 at 13 17 03](https://user-images.githubusercontent.com/217240/211858850-c764721e-471a-4060-9250-2b16b451482d.png)

### Environment

 - OS: Mac
 - Node.js version: 16.3.1
 - NPM version: 8.1.2
 - Browser (if applicable): chrome

### Additional context
All the other tests work fine. This test also works fine without that call to `whithin`. 
The canvas element is there: 

```
console.log('play...', { canvasElement })
```

![Screen Shot 2023-01-11 at 13 19 51](https://user-images.githubusercontent.com/217240/211860020-6df345cd-a37f-46e8-94a4-79ad458cfb9c.png)

```
    "@storybook/addon-essentials": "^7.0.0-beta.15",
    "@storybook/addon-interactions": "^7.0.0-beta.15",
    "@storybook/addon-links": "^7.0.0-beta.15",
    "@storybook/blocks": "^7.0.0-beta.15",
    "@storybook/jest": "^0.0.10",
    "@storybook/nextjs": "^7.0.0-beta.15",
    "@storybook/react": "^7.0.0-beta.15",
    "@storybook/test-runner": "^0.9.2",
    "@storybook/testing-library": "^0.0.13",
```

**Comment by scottfuoco** [comment]
It looks like this is because you are using storybook v7.  The release notes for `@storybook/testing-library` show that support for storybook v7 is being added in `@storybook/testing-library` v0.0.14.

To get it working right now you can install the `next` release, currently it is `@storybook/testing-library@v0.0.14-next.1`.

You can check if there is a newer version of that when you go to install it here [https://github.com/storybookjs/testing-library/releases](https://github.com/storybookjs/testing-library/releases)

**Comment by yannbf** [comment]
Hey there! The latest versions of this library should not have this issue. Please upgrade them and let us know if you encounter issues. Thank you!
